spring:

  application:
    name: Task Manager
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      dialect: PostgresSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
